spring:
  application:
    name: llm
server:
  port: 7780
deepseek:
  url: https://api.deepseek.com/chat/completions
  model-name: deepseek-reasoner
  api-key: Bearer sk-45
  search-engine: https://api.tavily.com/search
  search-key: tvly-dev-pqjtn
esKnn:
  # 默认的 es 索引，无特殊需求不需要变动
  index-name: xxx
  # 默认的 es 匹配字段（匹配用户信息）
  es-field: content
  # 默认的 es 匹配字段（匹配向量）
  es-vector-field: content_vector
  match: match
  rule: and
  work-check: 45